name: Setup Project
description: Local composite action
inputs:
  python-version:
    description: Python version to use
    required: true
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
